name: CI/CD for Wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/assignment-acc:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/assignment-acc:latest

      - name: Install Minikube
        run: |
          Invoke-WebRequest -Uri "https://storage.googleapis.com/minikube/releases/latest/minikube-windows-amd64.exe" -OutFile "minikube.exe"
          Move-Item .\minikube.exe "C:\Windows\minikube.exe"

      - name: Start Minikube
        run: |
          minikube start --driver=docker --wait=true

      - name: Configure kubeconfig
        run: |
          minikube kubeconfig > $env:USERPROFILE\.kube\config
          kubectl config get-contexts

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml --validate=false
          kubectl apply -f k8s/service.yaml --validate=false
          kubectl apply -f k8s/ingress.yaml --validate=false
